// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eynqjmlpivxzfnhbbpms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5bnFqbWxwaXZ4emZuaGJicG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzM1MjEsImV4cCI6MjA2Nzk0OTUyMX0.ZF-Ds35E7otD2a6DI0Migg-T4xQgBkeIGgIpbzAwQiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});